# Generated by Django 5.2.13 on 2026-04-24 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0025_add_session_to_shared_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='is_shared_master',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='SharedPdfComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('text', models.TextField(blank=True, default='')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                (
                    'pdf',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='shared_comments', to='pdf.pdf'
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['page', 'creation_date'],
            },
        ),
    ]
